
// Globals
var popupDialogHolder;
var popupDialogText = ["","",""];
var popupDialogCallback;

/*
* Function to get a div dialog.
*
* @param name	node to set the border around
* @param left	(optional) left position
* @param top	(optional) top position
* @param width	(optional) width of div
* @param height	(optional) height of div
* @param zIndex	(optional) zIndex of div
*/
function getAreaHolder( name, left, top, width, height, zIndex )
{
	var area = document.getElementById( name );
	if(area == null)
	{
		area = document.createElement( "div" );
		area.setAttribute( "id", name );
		area.style.position = "absolute";
		if(left != undefined) area.style.left = left + "px";
		if(top != undefined) area.style.top = top + "px";
		if(width != undefined) area.style.width = width + "px";
		if(height != undefined) area.style.height = height + "px";
		if(zIndex != undefined) area.style.zIndex = zIndex;
		area.style.borderStyle = 'solid';
		area.style.borderColor = 'Black';
		area.style.borderWidth = 2;
		area.style.backgroundColor = "Grey";
		area.style.visibility = "hidden";
		document.body.insertBefore( area, document.body.firstChild.nextSibling );
	}
	return area;
}

/*
* Function to popup a dialog.
*
* @param callback	address of function to callback to
* @param title		title to display in Popup
* @param text		text to display under title
* @param bText		array of button names
*/
function popupQuestionBox( callback, title, text, bText, returnUserInput)
{
	returnUserInput = typeof returnUserInput !== 'undefined' ?  returnUserInput : false;
	var area = getAreaHolder( 'PopupDialogHolder', Math.floor( (((screen.width > 800)?800:screen.width) - 320) / 2),
							Math.floor( (((screen.height > 540)?540:screen.height) - 170) / 2), 320, 170, 999 );
	if(area != null)
	{
		var buttonImage = "iVBORw0KGgoAAAANSUhEUgAAACQAAAAgCAYAAAB6kdqOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAOxAAADsQBlSsOGwAAEitJREFUWAkBIBLf7QEAAAAAFRUbUwECAmT///4cAAEBAwECAQAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQECAQIBAf4DAgL6AwMEBP7/AZ/j4didAAAA9QAAAPwBHR8leUFCRm1DRUoQISIiCQMDAgAAAAAAAAAAAAAAAAAAAAEAAAEAAAAAAAAAAAAAAQEAAAEAAAAAAAEAAAAAAAEAAQAAAAAAAAEAAAAAAQABAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAA/wD/AP//AAD6+vr/+Pb3/+3u7f2Afnng/fv7r93b0o4AAADtASIlLtyRlJwiDQ0MAQcGBQAEBQMAAAAAAAAAAAABAAAAAAABAAABAAAAAAEAAAAAAAEBAAABAAEAAAAAAAABAAABAAEAAAAAAAABAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAD//wD//wAA+/z7APf2+AD09fYA6ejo/JaUkenNybxWAAAA1gQGBgYCAQEBAfz9/QAJAgYACQkIAAICAgAAAAAAAQAAAAAAAQAAAQAAAAABAAAAAAABAQAAAQABAAAAAAAAAQAAAQABAAAAAAAAAQAAAAABAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v7/APj4+AD19PYA+vr6AAYHCAQHBwgEAAAAHQAAAOIEBQUGA/n6+gACAwIA/QgHABUTDQAWEgwA//8AAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAP79/wDd4uwA+vr6APj3+AD4+PgABQYGAgAAAAkAAAAEBAMDBgH7+/wAAwL6APj5+gDu7/YA9vb7APv8/gD/AP8AAQAAAAAAAAAAAQEAAQAAAAAAAAAAAQEAAAAAAAEBAQAAAAAAAAABAAEBAAAAAAAAAQABAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAEBAAACAgEA+Pn6APb3+AD4+foA+vr8AAIEBQIAAAAAAAAAAAQCAgIB//7+AP7+/wD///4A/v7/APv8/QAA/wAAAQEAAAEAAQAAAQAAAAEAAAEAAAAAAAEAAAEAAAAAAAABAAAAAQEBAAAAAAAAAQAAAAABAAEAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/v7/AAABAAD///8A//7+AP///gACAQIBAAAAAAAAAAAEAAAAAP8AAAABAf8AAAAAAAEBAAAAAAAAAQEAAAABAAABAAAAAAEAAAABAQABAAAAAAAAAAABAQABAAAAAAAAAAEBAAAAAAEAAAEAAAAAAAABAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAEBAAAAAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAQEAAAEBAQAAAAAAAQEAAAAAAAAAAQAAAQAAAAAAAQABAQEAAAAAAAABAAABAAEAAAAAAAEBAQAAAAAAAAEBAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAEBAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAQAAAAAAAAABAAAAAQEBAAEBAQABAQAAAQAAAAEBAQAAAAAAAAEBAAEAAAAAAQEAAQEAAAAAAQAAAAAAAQEBAAAAAAABAQEAAAAAAAAAAQAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAAAAAQEAAQEBAAEBAQAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAQEBAAEBAAABAQAAAQEBAAEAAAABAQEAAQEAAAABAQABAAAAAAEBAAEAAAAAAAEAAAEAAAEBAQAAAAAAAQEBAAEAAAAAAAEAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAQIAAgEAAAEBAAAAAAAAAAAAAAAAAAAAAAAABAAAAAABAQAAAQEAAAAAAAACAQEAAQEBAAIBAAABAQAAAQEAAAEBAQAAAQEAAQAAAAABAAABAAEAAQABAAABAAAAAQEAAQAAAAABAQABAAAAAAABAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAAAAgIBAAEBAQABAQEAAQEBAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAABAgEAAQEAAAIBAAACAgEAAQAAAAECAQABAQEAAAEBAAIBAQAAAAAAAQEAAAABAQAAAAEAAQAAAAEAAQAAAQEAAQEAAAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAAICAQACAgEAAQEAAAEBAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAQAAAQEAAAEBAAABAQEAAQEBAAEBAAACAgEAAQAAAAECAAABAQAAAQABAAABAAABAQEAAAABAAEAAAAAAAEAAAEBAAEBAAAAAAEAAAEAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wACAgEAAQEBAAEBAQABAQAAAAAAAAAAAAAAAAAABAAAAAAAAAEAAQAAAAEAAAABAQEAAgEBAAIBAAABAQEAAgEBAAEBAAABAQEAAQIBAAEAAAAAAQEAAQABAAAAAQABAQAAAQEBAAAAAQAAAQAAAAABAAABAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAwEBAAIBAAABAAAAAQABAAAAAAAAAAAAAAAAAAQAAAAAAQEAAAEAAAAAAAAAAQEAAAEBAAABAQEAAgIBAAIBAAAAAQEAAQIBAAEBAQACAAAAAAEBAAEBAQAAAAEAAQEAAAABAQAAAAEAAQEAAAAAAQABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAECAAABAQEAAQEBAAABAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAEAAQABAQAAAQEAAAEBAAABAQEAAQEAAAABAQACAQEAAQEAAAAAAQABAQEAAQABAAABAAABAQEAAAABAAEBAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BAQABAQEAAAEBAAEBAAABAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAEAAAAAAAAAAQAAAAEBAAEBAAACAAEAAQEAAAEBAgAAAQAAAQEAAAEAAQAAAQAAAQEAAAEAAAAAAQEAAQEAAAAAAAABAQEAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQEBAAEBAAAAAAAAAQEBAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAABAAAAAQAAAAEAAAABAQEAAAEAAAABAQAAAQAAAQAAAAEBAAABAAEAAAEAAAEBAQABAAEAAAEBAAEBAAAAAAEAAQEBAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAEBAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAABAAAAAAAAAAEAAAABAAABAAAAAAAAAAAAAAABAAAAAQEAAAEBAQAAAAEAAQEAAAABAAABAQAAAQAAAAABAAABAQAAAAAAAAEBAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAP//AAABAQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAEAAAAAAAAAAAEAAAAAAAABAQAAAAEAAAAAAAABAAAAAQEAAAABAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEBAQEA//8AAP8AAP///wD/AP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA//8AAAAAAAD//wAA////AAEAAQAAAAAAAAAAAAIAAQEA/v7/AP3+/gD9/f4A/f3+AP///wD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA///+APz8/AD8/PwA/f39AP7+/gABAQEBAAAAAAAAAAAEBAMEAvn6+gD//v0AAAD/AP7+/gAHBgQAAwMDAAICAQACAgEAAQEAAAEAAQABAgEAAQEBAAAAAQAAAQAAAQAAAAAAAQABAQEAAQAAAAABAQAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//APz8/QDu7/IA7u7yAPX19wD5+vsABAMDAgAAAAAAAAAABAUGBwL39vcA9v//APDx8gDl5ukAAP//AAEBAQABAQAAAQEAAAAAAQABAQEAAAAAAAEBAAAAAAAAAAAAAAEBAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///wD+//8A+vr7APz7/AAAAAAA/wAAAAAAAAAAAAAAAAAAAAQFBgUD9vf4APz8/AD///4AAQEBAAEAAAAAAQAAAQABAAABAAABAAAAAAEBAAEAAAAAAAAAAAAAAAABAQABAAAAAAAAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPTz9P0AAAAAAAAAAAAAAAAC/wABsNbV1ff4+Pj/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPv8/P/HxsXx4N/ZvAAAAPYAAAD7AQAAABI5PkuFDQ4QTQICBQsBAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////86unkz87KvqsAAADTAAAA1gEAAAAFAAAAFQAAACIAAAAZAAAACQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAPgAAADlAAAA2wAAAO0BAAAAAAAAAAQAAAAMAAAACwAAAAQAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8AAAA9QAAAPQAAAD7mT5VSBfJY88AAAAASUVORK5CYII="
		
		area.innerHTML = "<div> "
				+ "<div><center><b>" + title + "</b></center></div><div style=\"position:absolute;left:10px;top:38px;width:300px;height:40" 
				+ "\">" + text + "</div><div style=\"position:absolute;visibility:hidden;left:85px;top:5;width:290px;height:80\"><input type=\"text\" id=\"popUpUserInput\" onmousedown=\" xrxGetKeyboard().load('popUpUserInput') \"></div><div style=\"position:absolute;left:15px;top:90px;width:290px;height:80\">" 
				+ ((bText.length == 5)?"<div style=\"position:absolute;left:0px;top:0px;width:54px;height:15\"><center>" + (popupDialogText[0] = bText[0]) 
				+ "</center></div><div style=\"position:absolute;left:0px;top:20px;width:54px;height:40\"><center><img id=\"DialogB0\" src=\"data:image/jpeg;base64," + buttonImage + "\" "
				+ "width=\"50\" height=\"40\" onmousedown=\"popupQuestionButton(0);\"></img></center></div>":"") 
				+ ((bText.length > 1)?"<div style=\"position:absolute;left:59px;top:0px;width:54px;height:15\"><center>" + (popupDialogText[1] = 
				((bText.length == 5)?bText[1]:bText[0])) + "</center></div><div style=\"position:absolute;left:59px;top:20px;width:54px;height:40\"><center><img "
				+ "id=\"DialogB1\" src=\"data:image/jpeg;base64," + buttonImage + "\" width=\"50\" height=\"40\" onmousedown=\"popupQuestionButton"
				+ "(1);\"></img></center></div>":"")
				+ ((bText.length != 2)?"<div style=\"position:absolute;left:118px;top:0px;width:54px;height:15\"><center>" + (popupDialogText[2] = ((bText.length == 1)?
				bText[0]:((bText.length == 5)?bText[2]:bText[1]))) + "</center></div><div style=\"position:absolute;left:118px;top:20px;width:54px;height:40\">"
				+ "<center><img id=\"DialogB2\" src=\"data:image/jpeg;base64," + buttonImage + "\" width=\"50\" height=\"40\" "
				+ "onmousedown=\"popupQuestionButton(2, " + returnUserInput + ");\"></img></center></div>":"")
				+ ((bText.length > 1)?"<div style=\"position:absolute;left:177px;top:0px;width:54px;height:15\"><center>" + (popupDialogText[3] = ((bText.length == 2)?
				bText[1]:((bText.length == 5)?bText[3]:bText[2]))) + "</center></div><div style=\"position:absolute;left:177px;top:20px;width:54px;height:40\">"
				+ "<center><img id=\"DialogB3\" src=\"data:image/jpeg;base64," + buttonImage + "\" width=\"50\" height=\"40\" "
				+ "onmousedown=\"popupQuestionButton(3);\"></img></center></div>":"")
				+ ((bText.length > 3)?"<div style=\"position:absolute;left:236px;top:0px;width:54px;height:15\"><center>" + (popupDialogText[4] = ((bText.length == 4)?
				bText[3]:bText[4])) + "</center></div><div style=\"position:absolute;left:236px;top:20px;width:54px;height:40\"><center><img id=\"DialogB4\" "
				+ "src=\"data:image/jpeg;base64," + buttonImage + "\" width=\"50\" height=\"40\" onmousedown=\"popupQuestionButton(4);\"></img>"
				+ "</center></div>":"") + "</div>";
		popupDialogCallback = callback;
		if(returnUserInput) document.getElementById("popUpUserInput").style.visibility = "visible"; 
		(popupDialogHolder = area).style.visibility = "visible";
	}
}

/*
* Callback point of popup that calls the user's callback.
*
* @param index	index of button names that was selected
*/
function popupQuestionButton( index , returnUserInput)
{
	returnUserInput = typeof returnUserInput !== 'undefined' ?  returnUserInput : false;
	if (returnUserInput) var userInput = document.getElementById("popUpUserInput").value;
	popupDialogHolder.innerHTML = "";
	popupDialogHolder.style.visibility = "hidden";	
	if((popupDialogCallback != undefined) && (popupDialogCallback != null)) popupDialogCallback( returnUserInput ? userInput : popupDialogText[index] );
}

/*
* Function to put up a Yes and No dialog.
*
* @param msg		message to display
* @param callback	function point to callback to with answer
*/
function popupYesNo( msg, callback )
{
	popupQuestionBox( callback, msg, "", ["Yes","No"] );
}
/*
* Function to put up an OK dialog.
*
* @param msg		message to display
* @param callback	(optional) function point to callback to
*/
function popupOk( msg, callback )
{
	popupQuestionBox( callback, msg, "", ["OK"] );
}
/*
* Function to put up an OK prompt dialog that allows for user input.
*
* @param msg		message to display
* @param callback	(optional) function point to callback to with user input
*/
function popupPrompt(msg, callback)
{
	popupQuestionBox( callback, "", msg, ["OK"], true );
}
